@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inl5eXl5MSIsImlhdCI6MTY3NjE3ODU1NCwiZXhwIjoxNjc2MTgyMTU0fQ.XUO01JfttxuJXei14CJQyPAvxlOKGu8PqEDJFpgfM-4
### Sign up
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "username": "yyyyy1",
  "password": "9l`DSl^ecF>Bp"
}

### Sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "username": "yyyyy1",
  "password": "9l`DSl^ecF>Bp"
}



### Find all tasks
GET http://localhost:3000/tasks
Authorization: Bearer {{token}}


### Find a task by ID
GET http://localhost:3000/tasks/3b0f7d48-d05b-4b2e-80dd-984e0797d98f

### Find a task by keyword
GET http://localhost:3000/tasks?search=kb

### Create a new task
POST http://localhost:3000/tasks
content-type: application/json
Authorization: Bearer {{token}}

{
  "title": "kkk",
  "description": "bkkkb"
}

### Update a task
PATCH http://localhost:3000/tasks/3b0f7d48-d05b-4b2e-80dd-984e0797d98f/status
content-type: application/json
Authorization: Bearer {{token}}

{
  "status": "DONE"
}

### Delete a task by ID
DELETE  http://localhost:3000/tasks/2fcc28ca-1014-42cf-bf8e-a209b874f359